const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('iptvAPI', {
    parseM3u: (source, epgSource, mappings, forceRefresh) => ipcRenderer.invoke('parse-m3u', source, epgSource, mappings, forceRefresh),
    getEpgChannels: (epg) => ipcRenderer.invoke('get-epg-channels', epg),
    updateEpg: (epgSources, filterIds, forceRefresh) => ipcRenderer.invoke('update-epg', epgSources, filterIds, forceRefresh),
    getEpg: (channelIds, startLimit, endLimit) => ipcRenderer.invoke('get-epg', channelIds, startLimit, endLimit),
    getMappings: () => ipcRenderer.invoke('get-mappings'),
    saveMapping: (title, epgId) => ipcRenderer.invoke('save-mapping', title, epgId),
    saveMappingsBulk: (mappings) => ipcRenderer.invoke('save-mappings-bulk', mappings),
    getExternalEpgs: () => ipcRenderer.invoke('get-external-epgs'),
    addExternalEpg: (url) => ipcRenderer.invoke('add-external-epg', url),
    removeExternalEpg: (url) => ipcRenderer.invoke('remove-external-epg', url),
    playMpvEmbedded: (data) => ipcRenderer.send('play-mpv-embedded', data),
    updateMpvBounds: (bounds) => ipcRenderer.send('update-mpv-bounds', bounds),
    sendMpvCommand: (cmd) => ipcRenderer.send('mpv-command', cmd),
    showNativeToast: (message, duration) => ipcRenderer.send('show-native-toast', message, duration),
    toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
    onFullscreenChange: (callback) => ipcRenderer.on('fullscreen-state', (_event, isFull) => callback(isFull)),
    onMpvPropChange: (callback) => ipcRenderer.on('mpv-prop-change', (_event, name, val) => callback(name, val)),
    onMpvExit: (callback) => ipcRenderer.on('mpv-exit', (_event, code) => callback(code)),
    onMpvStopped: (callback) => ipcRenderer.on('mpv-stopped', () => callback()),
    onMpvFileLoaded: (callback) => ipcRenderer.on('mpv-file-loaded', () => callback()),
    onPreviousChannel: (callback) => ipcRenderer.on('mpv-previous-channel', callback),
    onNextChannel: (callback) => ipcRenderer.on('mpv-next-channel', callback),
    onMpvSelectAid: (callback) => ipcRenderer.on('mpv-select-aid', callback),
    onMpvSelectSid: (callback) => ipcRenderer.on('mpv-select-sid', callback),
    onStreamFailedRetry: (callback) => ipcRenderer.on('mpv-stream-failed-retry', callback),
    saveChannels: (channels) => ipcRenderer.invoke('save-channels', channels),
    deletePlaylist: (playlistId) => ipcRenderer.invoke('delete-playlist', playlistId),
    clearAllPlaylists: () => ipcRenderer.invoke('clear-all-playlists'),
    loadChannels: () => ipcRenderer.invoke('load-channels'),
    openFileDialog: () => ipcRenderer.invoke('open-file-dialog'),
    clearCache: (url) => ipcRenderer.invoke('clear-cache', url),
    factoryReset: () => ipcRenderer.invoke('factory-reset'),
    hideSplash: () => ipcRenderer.send('hide-splash'),
    getIpAddress: () => ipcRenderer.invoke('get-ip-address'),
    copyToClipboard: (text) => ipcRenderer.send('copy-to-clipboard', text),
    getRemoteSettings: () => ipcRenderer.invoke('get-remote-settings'),
    saveRemoteSettings: (settings) => ipcRenderer.invoke('save-remote-settings', settings),
    onRemotePlayChannel: (callback) => ipcRenderer.on('remote-play-channel', (_event, info) => callback(info)),
    onRemoteSettingsUpdated: (callback) => ipcRenderer.on('remote-settings-updated', callback),
    onRemoteError: (callback) => ipcRenderer.on('remote-error', (_event, msg) => callback(msg)),
    onRemoteAction: (callback) => ipcRenderer.on('remote-action', (_event, cmd) => callback(cmd)),
    onShowRemoteOverrideToast: (callback) => ipcRenderer.on('show-remote-override-toast', (_event, deviceId) => callback(deviceId)),
    sendRemoteOverrideResponse: (allow) => ipcRenderer.send('remote-override-response', allow),
    onRemoteSearch: (callback) => ipcRenderer.on('remote-search', (_event, text) => callback(text)),
    syncRemoteSearch: (text) => ipcRenderer.send('sync-remote-search', text),
    focusRemoteSearch: () => ipcRenderer.send('focus-remote-search'),
    parseStalker: (params) => ipcRenderer.invoke('parse-stalker', params),
    getStalkerEpisodes: (params) => ipcRenderer.invoke('get-stalker-episodes', params),
    resolveStalkerLink: (params) => ipcRenderer.invoke('resolve-stalker-link', params),
    loadStalkerCategory: (params) => ipcRenderer.invoke('load-stalker-category', params),
    parseXtream: (params) => ipcRenderer.invoke('parse-xtream', params),
    resolveXtreamLink: (params) => ipcRenderer.invoke('resolve-xtream-link', params),
    getTelemetryDiagnostics: (portalUrl) => ipcRenderer.invoke('get-telemetry-diagnostics', portalUrl),
    getTmdbConfig: () => ipcRenderer.invoke('get-tmdb-config'),
    saveTmdbConfig: (config) => ipcRenderer.invoke('save-tmdb-config', config),
    fetchTmdbByTitle: (params) => ipcRenderer.invoke('fetch-tmdb-by-title', params),
    fetchTmdbById: (params) => ipcRenderer.invoke('fetch-tmdb-by-id', params),
    fetchTmdbSeasonEpisodes: (params) => ipcRenderer.invoke('fetch-tmdb-season-episodes', params),
    getPlaybackProgress: (id) => ipcRenderer.invoke('get-playback-progress', id),
    savePlaybackProgress: (params) => ipcRenderer.invoke('save-playback-progress', params),
    getAllPlaybackProgress: () => ipcRenderer.invoke('get-all-playback-progress'),
    startRecording: (channelUrl, channelName, programName, headers) => ipcRenderer.invoke('start-recording', channelUrl, channelName, programName, headers),
    stopRecording: (recordingId) => ipcRenderer.invoke('stop-recording', recordingId),
    getActiveRecordings: () => ipcRenderer.invoke('get-active-recordings'),
    getRecordings: () => ipcRenderer.invoke('get-recordings'),
    deleteRecording: (filename) => ipcRenderer.invoke('delete-recording', filename),
    onFullscreenChange: (callback) => ipcRenderer.on('fullscreen-state', (_event, isFull) => callback(isFull)),
    onMpvPropChange: (callback) => ipcRenderer.on('mpv-prop-change', (_event, name, val) => callback(name, val)),
    onMpvExit: (callback) => ipcRenderer.on('mpv-exit', (_event, code) => callback(code)),
    onMpvStopped: (callback) => ipcRenderer.on('mpv-stopped', () => callback()),
    onMpvFileLoaded: (callback) => ipcRenderer.on('mpv-file-loaded', () => callback()),
    onPreviousChannel: (callback) => ipcRenderer.on('mpv-previous-channel', callback),
    onNextChannel: (callback) => ipcRenderer.on('mpv-next-channel', callback),
    onStreamFailedRetry: (callback) => ipcRenderer.on('mpv-stream-failed-retry', callback),
    saveChannels: (channels) => ipcRenderer.invoke('save-channels', channels),
    deletePlaylist: (playlistId) => ipcRenderer.invoke('delete-playlist', playlistId),
    clearAllPlaylists: () => ipcRenderer.invoke('clear-all-playlists'),
    loadChannels: () => ipcRenderer.invoke('load-channels'),
    openFileDialog: () => ipcRenderer.invoke('open-file-dialog'),
    clearCache: (url) => ipcRenderer.invoke('clear-cache', url),
    factoryReset: () => ipcRenderer.invoke('factory-reset'),
    hideSplash: () => ipcRenderer.send('hide-splash'),
    getIpAddress: () => ipcRenderer.invoke('get-ip-address'),
    copyToClipboard: (text) => ipcRenderer.send('copy-to-clipboard', text),
    getRemoteSettings: () => ipcRenderer.invoke('get-remote-settings'),
    saveRemoteSettings: (settings) => ipcRenderer.invoke('save-remote-settings', settings),
    onRemotePlayChannel: (callback) => ipcRenderer.on('remote-play-channel', (_event, info) => callback(info)),
    onRemoteSettingsUpdated: (callback) => ipcRenderer.on('remote-settings-updated', callback),
    onRemoteError: (callback) => ipcRenderer.on('remote-error', (_event, msg) => callback(msg)),
    onRemoteAction: (callback) => ipcRenderer.on('remote-action', (_event, cmd) => callback(cmd)),
    onShowRemoteOverrideToast: (callback) => ipcRenderer.on('show-remote-override-toast', (_event, deviceId) => callback(deviceId)),
    sendRemoteOverrideResponse: (allow) => ipcRenderer.send('remote-override-response', allow),
    onRemoteSearch: (callback) => ipcRenderer.on('remote-search', (_event, text) => callback(text)),
    syncRemoteSearch: (text) => ipcRenderer.send('sync-remote-search', text),
    focusRemoteSearch: () => ipcRenderer.send('focus-remote-search'),
    parseStalker: (params) => ipcRenderer.invoke('parse-stalker', params),
    getStalkerEpisodes: (params) => ipcRenderer.invoke('get-stalker-episodes', params),
    resolveStalkerLink: (params) => ipcRenderer.invoke('resolve-stalker-link', params),
    loadStalkerCategory: (params) => ipcRenderer.invoke('load-stalker-category', params),
    parseXtream: (params) => ipcRenderer.invoke('parse-xtream', params),
    resolveXtreamLink: (params) => ipcRenderer.invoke('resolve-xtream-link', params),
    getTelemetryDiagnostics: (portalUrl) => ipcRenderer.invoke('get-telemetry-diagnostics', portalUrl),
    getTmdbConfig: () => ipcRenderer.invoke('get-tmdb-config'),
    saveTmdbConfig: (config) => ipcRenderer.invoke('save-tmdb-config', config),
    fetchTmdbByTitle: (params) => ipcRenderer.invoke('fetch-tmdb-by-title', params),
    fetchTmdbById: (params) => ipcRenderer.invoke('fetch-tmdb-by-id', params),
    fetchTmdbSeasonEpisodes: (params) => ipcRenderer.invoke('fetch-tmdb-season-episodes', params),
    getPlaybackProgress: (id) => ipcRenderer.invoke('get-playback-progress', id),
    savePlaybackProgress: (params) => ipcRenderer.invoke('save-playback-progress', params),
    getAllPlaybackProgress: () => ipcRenderer.invoke('get-all-playback-progress'),
    startRecording: (channelUrl, channelName, programName, headers) => ipcRenderer.invoke('start-recording', channelUrl, channelName, programName, headers),
    stopRecording: (recordingId) => ipcRenderer.invoke('stop-recording', recordingId),
    getActiveRecordings: () => ipcRenderer.invoke('get-active-recordings'),
    getRecordings: () => ipcRenderer.invoke('get-recordings'),
    deleteRecording: (filename) => ipcRenderer.invoke('delete-recording', filename),
    getRecordingPath: () => ipcRenderer.invoke('get-recording-path'),
    saveRecordingPath: (path) => ipcRenderer.invoke('save-recording-path', path),
    onRecordingStatusChange: (callback) => ipcRenderer.on('recording-status-change', (_event, data) => callback(data)),
    scheduleRecording: (channelUrl, channelName, programName, startTime, endTime, headers) => ipcRenderer.invoke('schedule-recording', channelUrl, channelName, programName, startTime, endTime, headers),
    getScheduledRecordings: () => ipcRenderer.invoke('get-scheduled-recordings'),
    cancelScheduledRecording: (scheduleId) => ipcRenderer.invoke('cancel-scheduled-recording', scheduleId),
    minimizeWindow: () => ipcRenderer.send('window-minimize'),
    maximizeWindow: () => ipcRenderer.send('window-maximize'),
    closeWindow: () => ipcRenderer.send('window-close'),
    setConfirmToastActive: (active) => ipcRenderer.send('set-confirm-toast-active', active),
    closeMpvTrackSelector: () => ipcRenderer.send('close-mpv-track-selector'),
    log: (category, level, message) => ipcRenderer.send('write-log', { category, level, message })
});
